### PR TITLE
Added readme

### PR DESCRIPTION
**Pull request by sahithyandev**

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
@sahithyandev  Hey I think you missed the initial 3 installation steps in the description. npm i -g nodepass won't work since it is not in the npm registrar. Thus you will have to clone the repository. Go to the project folder run npm install and npm link then it will be available globally

**Comment by sahithyandev** [comment]
@ChinmayMhatre Oh.. I didn't realize that you haven't published it to npm yet. Let me know if you have any plans on publishing it to npm.

I will fix the README soon.

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre Oh.. I didn't realize that you haven't published it to npm yet. Let me know if you have any plans on publishing it to npm.
> 
> I will fix the README soon.

No worries! Yes I'll let you know.

**Comment by ChinmayMhatre** [comment]
LGTM! Thank you for your contribution!! #1

**Pull request merged**
